version: '3.8'
services:
  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    networks:
      - optiq_prod

networks:
  optiq_prod:
    name: optiq_prod
    external: true
