version: '3.8'
services:
  landing-page:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: always
    networks:
      - optiq_prod

networks:
  optiq_prod:
    name: optiq_prod
    external: true
